/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tiedoston.tiivistys;

import org.junit.Test;
import static org.junit.Assert.*;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.HashSet;
import java.util.Scanner;
import java.util.Set;

import org.junit.Before;

public class HuffmanTest {

    Huffman huffman;
    Set<String> joukko;

    @Before
    public void setUp() throws FileNotFoundException {
        huffman = new Huffman("testFile.txt");
        huffman.kompressoi();

        Scanner lukija = new Scanner(new File("testFile.txt"));
        joukko = new HashSet<String>();
        while (lukija.hasNextLine()) {
            String rivi = lukija.nextLine();
            String[] merkit = rivi.split("");
            for (String merkki : merkit) {
                joukko.add(merkki);
            }
        }
    }

    @Test
    public void testKaikkiMerkit() {
        assertEquals(huffman.merkkienMaarat.keySet(), joukko);
    }
}
